DSN ?= postgresql+psycopg2://crawler:crawler@postgres:5432/crawlerdb
URL_FILE ?= /app/seeds/urls.txt
NUM_SHARDS ?= 256
SHARDS_PER_INGESTOR ?= 16
INGEST_SERVICE ?= scheduler_ingest
RESULT_MINUTES ?= 60
RESULT_LABEL ?= run
EXPERIMENT_LABEL ?= quick
EXPERIMENT_URL_FILE ?= seeds/urls.txt
EXPERIMENT_LIMIT ?=
EXPERIMENT_BATCH_SIZE ?= 100
EXPERIMENT_CRAWLER_ID ?= 0
SMALL_URL_FILE ?= /app/seeds/urls.txt
SMALL_NUM_SHARDS ?= 256
SMALL_SHARDS_PER_INGESTOR ?= 256
SMALL_INGEST_SERVICE ?= scheduler_ingest
SMALL_POSTGRES_MAX_CONNECTIONS ?= 50
SMALL_POSTGRES_MAX_WAL_SIZE ?= 1GB
SMALL_POSTGRES_CHECKPOINT_TIMEOUT ?= 5min
SMALL_SCHEDULER_CONTROL_CONFIG ?= /app/containers/scheduler_control/config/control.small.yaml
SMALL_SCHEDULER_INGEST_CONFIG ?= /app/containers/scheduler_ingest/config/ingest.small.yaml
SMALL_SCHEDULER_CONTROL_OFFERER_PROCS ?= 1
SMALL_SCHEDULER_INGEST_ROUTER_PROCS ?= 1
SMALL_SCHEDULER_INGEST_INGESTOR_PROCS ?= 1
SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS ?= 1
SMALL_CRAWLER_NUMPROCS ?= 1
SMALL_CRAWLER_CONCURRENT_REQUESTS ?= 8
SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN ?= 2
SMALL_CRAWLER_DOWNLOAD_DELAY ?= 1.0
SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY ?= 1.0
SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY ?= 15.0
SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY ?= 1.0
SMALL_CRAWLER_LOG_LEVEL ?= WARNING
BENCHMARK_LABEL ?=
BENCHMARK_HOURS ?= 6
BENCHMARK_SECONDS ?=
BENCHMARK_RESET ?= false
BENCHMARK_DOMAIN_QPS_LOG_ENABLED ?= true
BENCHMARK_DOMAIN_QPS_LOG_INTERVAL ?= 1.0
BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS ?= 5.0

.PHONY: bootstrap init-db seed-urls repair-crawl-flags up-postgres up crawler-fixed crawler-autothrottle summarize-crawl experiment-fixed experiment-autothrottle bootstrap-small up-small crawler-fixed-small crawler-autothrottle-small benchmark-small-fixed benchmark-small-autothrottle benchmark-small-compare

bootstrap:
	bash scripts/bootstrap.sh

up-postgres:
	docker compose up -d postgres

init-db:
	docker compose run --rm $(INGEST_SERVICE) \
		python /app/scripts/init_db.py \
		--dsn "$(DSN)" \
		--num-shards "$(NUM_SHARDS)"

seed-urls:
	docker compose run --rm $(INGEST_SERVICE) \
		python /app/scripts/seed_urls.py \
		--dsn "$(DSN)" \
		--file "$(URL_FILE)" \
		--num-shards "$(NUM_SHARDS)" \
		--shards-per-ingestor "$(SHARDS_PER_INGESTOR)"

repair-crawl-flags:
	docker compose run --rm $(INGEST_SERVICE) \
		python /app/scripts/repair_crawl_flags.py \
		--dsn "$(DSN)" \
		--num-shards "$(NUM_SHARDS)"

up:
	docker compose up -d

bootstrap-small:
	POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	URL_FILE="$(SMALL_URL_FILE)" \
	NUM_SHARDS="$(SMALL_NUM_SHARDS)" \
	SHARDS_PER_INGESTOR="$(SMALL_SHARDS_PER_INGESTOR)" \
	INGEST_SERVICE="$(SMALL_INGEST_SERVICE)" \
	bash scripts/bootstrap.sh

up-small:
	POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	docker compose up -d

crawler-fixed:
	CRAWLER_USE_AUTOTHROTTLE=false docker compose up -d --force-recreate crawler

crawler-autothrottle:
	CRAWLER_USE_AUTOTHROTTLE=true docker compose up -d --force-recreate crawler

crawler-fixed-small:
	POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	CRAWLER_USE_AUTOTHROTTLE=false docker compose up -d --force-recreate crawler

crawler-autothrottle-small:
	POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	CRAWLER_USE_AUTOTHROTTLE=true docker compose up -d --force-recreate crawler

benchmark-small-fixed:
	BENCHMARK_LABEL="$(BENCHMARK_LABEL)" \
	BENCHMARK_HOURS="$(BENCHMARK_HOURS)" \
	BENCHMARK_SECONDS="$(BENCHMARK_SECONDS)" \
	BENCHMARK_RESET="$(BENCHMARK_RESET)" \
	BENCHMARK_DOMAIN_QPS_LOG_ENABLED="$(BENCHMARK_DOMAIN_QPS_LOG_ENABLED)" \
	BENCHMARK_DOMAIN_QPS_LOG_INTERVAL="$(BENCHMARK_DOMAIN_QPS_LOG_INTERVAL)" \
	BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS="$(BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS)" \
	SMALL_URL_FILE="$(SMALL_URL_FILE)" \
	SMALL_NUM_SHARDS="$(SMALL_NUM_SHARDS)" \
	SMALL_SHARDS_PER_INGESTOR="$(SMALL_SHARDS_PER_INGESTOR)" \
	SMALL_INGEST_SERVICE="$(SMALL_INGEST_SERVICE)" \
	SMALL_POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	SMALL_POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	SMALL_POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SMALL_SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SMALL_SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SMALL_SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SMALL_SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SMALL_SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	SMALL_CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	SMALL_CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	SMALL_CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	bash scripts/run_small_benchmark.sh fixed

benchmark-small-autothrottle:
	BENCHMARK_LABEL="$(BENCHMARK_LABEL)" \
	BENCHMARK_HOURS="$(BENCHMARK_HOURS)" \
	BENCHMARK_SECONDS="$(BENCHMARK_SECONDS)" \
	BENCHMARK_RESET="$(BENCHMARK_RESET)" \
	BENCHMARK_DOMAIN_QPS_LOG_ENABLED="$(BENCHMARK_DOMAIN_QPS_LOG_ENABLED)" \
	BENCHMARK_DOMAIN_QPS_LOG_INTERVAL="$(BENCHMARK_DOMAIN_QPS_LOG_INTERVAL)" \
	BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS="$(BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS)" \
	SMALL_URL_FILE="$(SMALL_URL_FILE)" \
	SMALL_NUM_SHARDS="$(SMALL_NUM_SHARDS)" \
	SMALL_SHARDS_PER_INGESTOR="$(SMALL_SHARDS_PER_INGESTOR)" \
	SMALL_INGEST_SERVICE="$(SMALL_INGEST_SERVICE)" \
	SMALL_POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	SMALL_POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	SMALL_POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SMALL_SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SMALL_SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SMALL_SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SMALL_SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SMALL_SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	SMALL_CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	SMALL_CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	SMALL_CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	bash scripts/run_small_benchmark.sh autothrottle

benchmark-small-compare:
	BENCHMARK_LABEL="$(BENCHMARK_LABEL)" \
	BENCHMARK_HOURS="$(BENCHMARK_HOURS)" \
	BENCHMARK_SECONDS="$(BENCHMARK_SECONDS)" \
	BENCHMARK_RESET="$(BENCHMARK_RESET)" \
	BENCHMARK_DOMAIN_QPS_LOG_ENABLED="$(BENCHMARK_DOMAIN_QPS_LOG_ENABLED)" \
	BENCHMARK_DOMAIN_QPS_LOG_INTERVAL="$(BENCHMARK_DOMAIN_QPS_LOG_INTERVAL)" \
	BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS="$(BENCHMARK_DOMAIN_QPS_WINDOW_SECONDS)" \
	SMALL_URL_FILE="$(SMALL_URL_FILE)" \
	SMALL_NUM_SHARDS="$(SMALL_NUM_SHARDS)" \
	SMALL_SHARDS_PER_INGESTOR="$(SMALL_SHARDS_PER_INGESTOR)" \
	SMALL_INGEST_SERVICE="$(SMALL_INGEST_SERVICE)" \
	SMALL_POSTGRES_MAX_CONNECTIONS="$(SMALL_POSTGRES_MAX_CONNECTIONS)" \
	SMALL_POSTGRES_MAX_WAL_SIZE="$(SMALL_POSTGRES_MAX_WAL_SIZE)" \
	SMALL_POSTGRES_CHECKPOINT_TIMEOUT="$(SMALL_POSTGRES_CHECKPOINT_TIMEOUT)" \
	SMALL_SCHEDULER_CONTROL_CONFIG="$(SMALL_SCHEDULER_CONTROL_CONFIG)" \
	SMALL_SCHEDULER_INGEST_CONFIG="$(SMALL_SCHEDULER_INGEST_CONFIG)" \
	SMALL_SCHEDULER_CONTROL_OFFERER_PROCS="$(SMALL_SCHEDULER_CONTROL_OFFERER_PROCS)" \
	SMALL_SCHEDULER_INGEST_ROUTER_PROCS="$(SMALL_SCHEDULER_INGEST_ROUTER_PROCS)" \
	SMALL_SCHEDULER_INGEST_INGESTOR_PROCS="$(SMALL_SCHEDULER_INGEST_INGESTOR_PROCS)" \
	SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS="$(SMALL_SCHEDULER_INGEST_EXTRACTOR_PROCS)" \
	SMALL_CRAWLER_NUMPROCS="$(SMALL_CRAWLER_NUMPROCS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS="$(SMALL_CRAWLER_CONCURRENT_REQUESTS)" \
	SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(SMALL_CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	SMALL_CRAWLER_DOWNLOAD_DELAY="$(SMALL_CRAWLER_DOWNLOAD_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(SMALL_CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(SMALL_CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	SMALL_CRAWLER_LOG_LEVEL="$(SMALL_CRAWLER_LOG_LEVEL)" \
	bash scripts/run_small_benchmark_compare.sh

summarize-crawl:
	python3 scripts/summarize_crawl_results.py \
		--minutes "$(RESULT_MINUTES)" \
		--label "$(RESULT_LABEL)"

experiment-fixed:
	EXPERIMENT_LABEL="$(EXPERIMENT_LABEL)" \
	URL_FILE="$(EXPERIMENT_URL_FILE)" \
	EXPERIMENT_LIMIT="$(EXPERIMENT_LIMIT)" \
	EXPERIMENT_BATCH_SIZE="$(EXPERIMENT_BATCH_SIZE)" \
	EXPERIMENT_CRAWLER_ID="$(EXPERIMENT_CRAWLER_ID)" \
	CRAWLER_CONCURRENT_REQUESTS="$(CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_AUTOTHROTTLE_START_DELAY="$(CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	CRAWLER_AUTOTHROTTLE_DEBUG="$(CRAWLER_AUTOTHROTTLE_DEBUG)" \
	CRAWLER_LOG_LEVEL="$(CRAWLER_LOG_LEVEL)" \
	CRAWLER_DOMAIN_QPS_LOG_ENABLED="$(CRAWLER_DOMAIN_QPS_LOG_ENABLED)" \
	CRAWLER_DOMAIN_QPS_LOG_INTERVAL="$(CRAWLER_DOMAIN_QPS_LOG_INTERVAL)" \
	CRAWLER_DOMAIN_QPS_WINDOW_SECONDS="$(CRAWLER_DOMAIN_QPS_WINDOW_SECONDS)" \
	bash scripts/run_crawler_experiment.sh fixed

experiment-autothrottle:
	EXPERIMENT_LABEL="$(EXPERIMENT_LABEL)" \
	URL_FILE="$(EXPERIMENT_URL_FILE)" \
	EXPERIMENT_LIMIT="$(EXPERIMENT_LIMIT)" \
	EXPERIMENT_BATCH_SIZE="$(EXPERIMENT_BATCH_SIZE)" \
	EXPERIMENT_CRAWLER_ID="$(EXPERIMENT_CRAWLER_ID)" \
	CRAWLER_CONCURRENT_REQUESTS="$(CRAWLER_CONCURRENT_REQUESTS)" \
	CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="$(CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN)" \
	CRAWLER_DOWNLOAD_DELAY="$(CRAWLER_DOWNLOAD_DELAY)" \
	CRAWLER_AUTOTHROTTLE_START_DELAY="$(CRAWLER_AUTOTHROTTLE_START_DELAY)" \
	CRAWLER_AUTOTHROTTLE_MAX_DELAY="$(CRAWLER_AUTOTHROTTLE_MAX_DELAY)" \
	CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="$(CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY)" \
	CRAWLER_AUTOTHROTTLE_DEBUG="$(CRAWLER_AUTOTHROTTLE_DEBUG)" \
	CRAWLER_LOG_LEVEL="$(CRAWLER_LOG_LEVEL)" \
	CRAWLER_DOMAIN_QPS_LOG_ENABLED="$(CRAWLER_DOMAIN_QPS_LOG_ENABLED)" \
	CRAWLER_DOMAIN_QPS_LOG_INTERVAL="$(CRAWLER_DOMAIN_QPS_LOG_INTERVAL)" \
	CRAWLER_DOMAIN_QPS_WINDOW_SECONDS="$(CRAWLER_DOMAIN_QPS_WINDOW_SECONDS)" \
	bash scripts/run_crawler_experiment.sh autothrottle
